version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      # Upload index.html với Content-Type chính xác
      - aws s3 cp build/index.html s3://stc-dynamic-website/index.html --content-type text/html
      # Upload phần còn lại
      - aws s3 sync build/ s3://stc-dynamic-website/ --exclude "index.html" --delete
artifacts:
  base-directory: build
  files:
    - '**/*'
